// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFc2hFuUZc_ELbnHreeykzEIjFCVDc-TQ',
    appId: '1:699863497825:web:697dc09354a72caebebe20',
    messagingSenderId: '699863497825',
    projectId: 'presensi-da0a8',
    authDomain: 'presensi-da0a8.firebaseapp.com',
    storageBucket: 'presensi-da0a8.appspot.com',
    measurementId: 'G-C9ZW766M0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsdNrDvjnwl0N5YR2MTg8Eqm635og_hwA',
    appId: '1:699863497825:android:f067218c03d3d584bebe20',
    messagingSenderId: '699863497825',
    projectId: 'presensi-da0a8',
    storageBucket: 'presensi-da0a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj02lxXEOuyZ0Y_0np3529NW7VVZFOQ1U',
    appId: '1:699863497825:ios:a2700f520416c9f8bebe20',
    messagingSenderId: '699863497825',
    projectId: 'presensi-da0a8',
    storageBucket: 'presensi-da0a8.appspot.com',
    iosBundleId: 'com.example.presensi',
  );
}
